use sstsdb;

SHOW WARNINGS;
LOAD DATA LOCAL INFILE 'Dow.csv' INTO TABLE stocks
  FIELDS TERMINATED BY ','
  ENCLOSED BY '"'; 

LOAD DATA LOCAL INFILE 'Nasdaq.csv' INTO TABLE stocks
  FIELDS TERMINATED BY ',';
